### ISSUE TITLE
初回時に条件を満たしていなかったレースが追加されてしまう

### ISSUE THREAD

**Issue by Hujzita** [HashidaTKS/GreatUma#1]
０時（初回）には複勝オッズが条件値より大きく、一覧に表示されていなかったレースが、
８時に情報更新を押したときに、条件を満たしたため、追加されて、初回取得時オッズが８時時点のオッズになっている。

初めの仕様ではこのレースは一覧に追加されなかったはずだが、
このレースの情報も実はほしいので、
初回取得時オッズのところに取得時間を追記して、
情報更新ごとに全レースサーチして追加する仕様がうれしい。

（情報更新の時は馬柱プラスだけしか見に行かない仕様なのだとしたら、
今回だけのの挙動バグかもしれないけど）

**Comment by HashidaTKS** [comment]
複数回情報更新した時に、一度でも条件を満たしたレースはすべて対象にしたい、であっていますか？
そうであれば、ちゃちゃっとできそうなので近々修正します。

取得時間（最初に条件を満たした時刻）は初回取得オッズのところではなくて、別カラムで追加する方が見やすそうなので、別カラムにしようと思います。

**Comment by Hujzita** [comment]
それであってます。

**Comment by HashidaTKS** [comment]
メモ;

毎回開催情報を取得しに行くと処理速度が懸念。

今は取得した開催情報や馬のデータを永続化していないので、永続化する。
永続化したものがあればそれを使う。

既に馬のデータがある状態なら、オッズだけあればよいから、オッズも馬柱を見に行くだけで更新できるはず。

**Comment by HashidaTKS** [comment]
https://github.com/HashidaTKS/GreatUma/releases/tag/alpha-2

実装してリリースした。
