### ISSUE TITLE
当日の０時３０分に自動で情報更新してほしい

### ISSUE THREAD

**Issue by Hujzita** [HashidaTKS/GreatUma#2]
ソフトが立ち上がっていれば、０時３０分にその日の情報更新（初回）を自動で行ってほしい。

**Comment by HashidaTKS** [comment]
追加します。

**Comment by HashidaTKS** [comment]
https://github.com/HashidaTKS/GreatUma/commit/58104ef7d256f7a8a7df4eb6004c817db62ba4d0

0:30 - 2:00の間に起動していたら自動で情報取得するようにしました。（未リリース）

とりあえずは今は上記の修正を入れていますが、2:00までの制限はいらないかもしれません。
0;30 - 2:00に一回というより、1時間ごとくらいに自動更新するようにした方が良いかもしれません。

**Comment by HashidaTKS** [comment]
結局、固定で夜間に実行するよりも、自動更新機能の方が良さそうなので、自動情報更新機能を追加し、この機能が有効な場合30分ごとに情報を更新するように修正した。

**Comment by HashidaTKS** [comment]
https://github.com/HashidaTKS/GreatUma/releases/tag/alpha-2

リリースした。
