### ISSUE TITLE
処理終了時にコマンドプロンプトのターミナルやクロームウィンドウを閉じてほしい

### ISSUE THREAD

**Issue by Hujzita** [HashidaTKS/GreatUma#3]
自分で落としてもたぶん問題ないんだろうけど、
残高照会とか１レースごとに押すことが想定されるので、
そのたびにちゃんと処理が終わったか見極めてウィンドウ閉じるの煩わしいので、
勝手に閉じてほしい

**Comment by HashidaTKS** [comment]
これはある程度バグ取りができたら、そもそもChromeのウィンドウが表示されないようにする予定です。

**Comment by HashidaTKS** [comment]
とはいえ、実行済みのChromeインスタンスが起動しているのも微妙なので、改善してみます。
（正直残り続けるのはいまいちと思っていたのですが、どうせデバッグ用なので開いていてもいいかと思って放置していました。）

**Comment by HashidaTKS** [comment]
https://github.com/HashidaTKS/GreatUma/commit/50ed2602e57f37bfa02bc0b055b6e1f2c34cd5c2

修正した（未リリース）。

**Comment by HashidaTKS** [comment]
https://github.com/HashidaTKS/GreatUma/releases/tag/alpha-2

リリースした。
