### ISSUE TITLE
自動購入が利かなかった

### ISSUE THREAD

**Issue by Hujzita** [HashidaTKS/GreatUma#5]
![スクリーンショット 2024-09-28 104136](https://github.com/user-attachments/assets/7b237170-c7db-49ac-a58c-10603af41fa8)

原因でありえそうなのは以下の行動
①10:40のレースに対して10:37に条件変更で-1から2に変更したから遅すぎた説
②違うPCでJRAのネット投票を開いていた

ちなみに10:38頃にこのレースのリアルタイムオッズを取りに行ってそうなウィンドウは自動で開いた。
（現在オッズ取得時刻は更新されなかった）

**Comment by HashidaTKS** [comment]
①の場合、発走まで3分以内なら、30秒ごとに購入しようとするはずなので、購入2分前とかに再度購入処理が走って結果的に成功しそうな気がしています。
②もありえると思います。

残高が取得できているので、ログイン設定はできていますよね。。。

**Comment by HashidaTKS** [comment]
再確認しましたが、仕様通りのように思います。

購入しても良いオッズよりも現在オッズが良い（高い）ときに購入する仕様ですが、10:40発走レースの現在オッズが1.9で、購入オッズに2を指定しているので、現在オッズが購入オッズより悪いので購入処理が走っていなかったのだと思います。

**Comment by HashidaTKS** [comment]
想定仕様の図を再確認しましたが、図には「購入オッズ >= 現在オッズの時購入」と書いてあるので、条件が逆でした。。。

ただ、これだと指定したオッズよりも条件が悪い時に購入することになるのですが、仕様としてはこれで正しいでしょうか？
正しいのであればそのように修正します。
もしくは購入条件をオッズの上限下限の範囲で指定できるように変更します。

**Comment by Hujzita** [comment]
当初の指定で正しいです。
単勝のオッズが低いほうが信頼度が高く勝率が高いという考えなので。
（購入するのは複勝なので、単勝の払い戻しが低くても馬券収支に影響しない）
というかそれだと-1の時に購入しないことは矛盾してませんか？

**Comment by HashidaTKS** [comment]
> （購入するのは複勝なので、単勝の払い戻しが低くても馬券収支に影響しない）

購入する馬券は単勝だと思っていました！（過去の履歴や仕様の図にも購入する馬券タイプは言及がなかったですね。。。）
今も購入しているのは単勝です。
なるほど、複勝を買うなら納得です。複勝を買うようにすることも含めて動作修正します。

> というかそれだと-1の時に購入しないことは矛盾してませんか？

仕様の図に「1未満の値を入力したときは必ず購入しない」という記載があったので、現在のように「購入オッズ <= 現在オッズの時購入」という仕様だと、そのままだと1未満の時は必ず購入してしまうので、1未満の値を特別視して、必ず購入しない値とするという話かと思っていました。

**Comment by Hujzita** [comment]
確かに言ってなかったですね。そして先週テストで買った馬券は単勝の払い戻しが1.1倍だったせいで
単勝を買ってることに気づきませんでした。失礼しました。

**Comment by HashidaTKS** [comment]
https://github.com/HashidaTKS/GreatUma/releases/tag/alpha-4

修正してリリースしました。

**Comment by HashidaTKS** [comment]
@Hujzita 

https://github.com/HashidaTKS/GreatUma/releases/tag/alpha-4

こちらを使用して改めて動作確認をお願いします。
alpha-2、alpha-3に上書きしても動くとは思うのですが（枠情報が表示されない可能性はあり）、念のためそうはせずにalpha-4をまっさらな状態で使用して、再度ChromeDriverの配置とログイン情報の入力をお願いします。

**Comment by Hujzita** [comment]
動作しました

**Comment by HashidaTKS** [comment]
確認ありがとうございます。クローズします。
