### ISSUE TITLE
発走したレースの情報を残しておいてほしい

### ISSUE THREAD

**Issue by Hujzita** [HashidaTKS/GreatUma#6]
発走したレースの行が、情報更新すると消えてしまうので、その日の夜まで残しておいてほしい。
ちなみに確認できてないけど、最初に条件を満たした後にオッズが変動して
条件を満たさなくなっても、行として残してほしい。

ちょっとバグなのか仕様なのか不明ですが。

**Comment by HashidaTKS** [comment]
> 発走したレースの行が、情報更新すると消えてしまうので、その日の夜まで残しておいてほしい。

残すようにします。

> ちなみに確認できてないけど、最初に条件を満たした後にオッズが変動して
> 条件を満たさなくなっても、行として残してほしい。
>
> ちょっとバグなのか仕様なのか不明ですが。

こちらはalpha-2のバグで、alpha-3で直しました。

**Comment by HashidaTKS** [comment]
> 発走したレースの行が、情報更新すると消えてしまうので、その日の夜まで残しておいてほしい。

alpha-3で意図せず翌日以降もデータが残るようになっていました。
alpha-4で前日のデータは削除するように再度修正します。

**Comment by HashidaTKS** [comment]
https://github.com/HashidaTKS/GreatUma/releases/tag/alpha-4

修正してリリースしました。

**Comment by HashidaTKS** [comment]
alpha-4に問題があることが分かったので再修正。

**Comment by HashidaTKS** [comment]
https://github.com/HashidaTKS/GreatUma/releases/tag/alpha-4

修正してリリースしました。

**Comment by HashidaTKS** [comment]
@Hujzita

https://github.com/HashidaTKS/GreatUma/releases/tag/alpha-4

こちらを使用して改めて動作確認をお願いします。
alpha-2、alpha-3に上書きしても動くとは思うのですが（枠情報が表示されない可能性はあり）、念のためそうはせずにalpha-4をまっさらな状態で使用して、再度ChromeDriverの配置とログイン情報の入力をお願いします。

**Comment by Hujzita** [comment]
動作しました

**Comment by HashidaTKS** [comment]
確認ありがとうございます。クローズします。
